<?php

namespace App\Entities;

class EiAlocadoTotalizacao extends AbstractEntity
{
	protected $datamap = [];
	protected $dates   = [
		'created_at',
		'updated_at',
		'deleted_at',
	];
	protected $casts   = [
        'id' => 'int',
        'id_alocado' => 'int',
        'periodo' => '?bool',
        'id_cuidador' => 'int',
        'cuidador' => '?string',
        'cargo' => '?string',
        'cargo_mes2' => '?string',
        'cargo_mes3' => '?string',
        'cargo_mes4' => '?string',
        'cargo_mes5' => '?string',
        'cargo_mes6' => '?string',
        'cargo_mes7' => '?string',
        'funcao' => '?string',
        'funcao_mes2' => '?string',
        'funcao_mes3' => '?string',
        'funcao_mes4' => '?string',
        'funcao_mes5' => '?string',
        'funcao_mes6' => '?string',
        'funcao_mes7' => '?string',
        'substituicao_semestral' => '?bool',
        'substituicao_eventual' => '?bool',
        'total_dias_mes1' => '?int',
        'total_dias_mes2' => '?int',
        'total_dias_mes3' => '?int',
        'total_dias_mes4' => '?int',
        'total_dias_mes5' => '?int',
        'total_dias_mes6' => '?int',
        'total_dias_mes7' => '?int',
        'dias_descontados_mes1' => '?time',
        'dias_descontados_mes2' => '?time',
        'dias_descontados_mes3' => '?time',
        'dias_descontados_mes4' => '?time',
        'dias_descontados_mes5' => '?time',
        'dias_descontados_mes6' => '?time',
        'dias_descontados_mes7' => '?time',
        'total_dias_sub1' => '?int',
        'total_dias_sub2' => '?int',
        'total_horas_mes1' => '?time',
        'total_horas_mes2' => '?time',
        'total_horas_mes3' => '?time',
        'total_horas_mes4' => '?time',
        'total_horas_mes5' => '?time',
        'total_horas_mes6' => '?time',
        'total_horas_mes7' => '?time',
        'total_horas_sub1' => '?time',
        'total_horas_sub2' => '?time',
        'horas_descontadas_mes1' => '?time',
        'horas_descontadas_mes2' => '?time',
        'horas_descontadas_mes3' => '?time',
        'horas_descontadas_mes4' => '?time',
        'horas_descontadas_mes5' => '?time',
        'horas_descontadas_mes6' => '?time',
        'horas_descontadas_mes7' => '?time',
        'horas_descontadas_sub1' => '?time',
        'horas_descontadas_sub2' => '?time',
        'total_horas_faturadas_mes1' => '?time',
        'total_horas_faturadas_mes2' => '?time',
        'total_horas_faturadas_mes3' => '?time',
        'total_horas_faturadas_mes4' => '?time',
        'total_horas_faturadas_mes5' => '?time',
        'total_horas_faturadas_mes6' => '?time',
        'total_horas_faturadas_mes7' => '?time',
        'total_horas_faturadas_sub1' => '?time',
        'total_horas_faturadas_sub2' => '?time',
        'total_descontos_mes1' => '?time',
        'total_descontos_mes2' => '?time',
        'total_descontos_mes3' => '?time',
        'total_descontos_mes4' => '?time',
        'total_descontos_mes5' => '?time',
        'total_descontos_mes6' => '?time',
        'total_descontos_mes7' => '?time',
        'total_descontos_sub1' => '?time',
        'total_descontos_sub2' => '?time',
        'valor_pagamento_mes1' => '?decimal',
        'valor_pagamento_mes2' => '?decimal',
        'valor_pagamento_mes3' => '?decimal',
        'valor_pagamento_mes4' => '?decimal',
        'valor_pagamento_mes5' => '?decimal',
        'valor_pagamento_mes6' => '?decimal',
        'valor_pagamento_mes7' => '?decimal',
        'valor_pagamento_sub1' => '?decimal',
        'valor_pagamento_sub2' => '?decimal',
        'valor_total_mes1' => '?decimal',
        'valor_total_mes2' => '?decimal',
        'valor_total_mes3' => '?decimal',
        'valor_total_mes4' => '?decimal',
        'valor_total_mes5' => '?decimal',
        'valor_total_mes6' => '?decimal',
        'valor_total_mes7' => '?decimal',
        'valor_total_sub1' => '?decimal',
        'valor_total_sub2' => '?decimal',
    ];
}
