<?php

namespace App\Entities;

class EiFaturamento extends AbstractEntity
{
	protected $datamap = [];
	protected $dates   = [
		'created_at',
		'updated_at',
		'deleted_at',
	];
	protected $casts   = [
        'id' => 'int',
        'id_alocacao' => 'int',
        'id_escola' => '?int',
        'escola' => 'string',
        'cargo' => 'string',
        'funcao' => 'string',
        'data_envio_solicitacao_mes1' => '?date',
        'data_envio_solicitacao_mes2' => '?date',
        'data_envio_solicitacao_mes3' => '?date',
        'data_envio_solicitacao_mes4' => '?date',
        'data_envio_solicitacao_mes5' => '?date',
        'data_envio_solicitacao_mes6' => '?date',
        'data_envio_solicitacao_mes7' => '?date',
        'data_envio_solicitacao_sub1' => '?date',
        'data_envio_solicitacao_sub2' => '?date',
        'data_aprovacao_mes1' => '?date',
        'data_aprovacao_mes2' => '?date',
        'data_aprovacao_mes3' => '?date',
        'data_aprovacao_mes4' => '?date',
        'data_aprovacao_mes5' => '?date',
        'data_aprovacao_mes6' => '?date',
        'data_aprovacao_mes7' => '?date',
        'data_aprovacao_sub1' => '?date',
        'data_aprovacao_sub2' => '?date',
        'data_impressao_mes1' => '?date',
        'data_impressao_mes2' => '?date',
        'data_impressao_mes3' => '?date',
        'data_impressao_mes4' => '?date',
        'data_impressao_mes5' => '?date',
        'data_impressao_mes6' => '?date',
        'data_impressao_mes7' => '?date',
        'data_impressao_sub1' => '?date',
        'data_impressao_sub2' => '?date',
        'horas_descontadas_mes1' => '?time',
        'horas_descontadas_mes2' => '?time',
        'horas_descontadas_mes3' => '?time',
        'horas_descontadas_mes4' => '?time',
        'horas_descontadas_mes5' => '?time',
        'horas_descontadas_mes6' => '?time',
        'horas_descontadas_mes7' => '?time',
        'horas_descontadas_sub1' => '?time',
        'horas_descontadas_sub2' => '?time',
        'observacoes_mes1' => '?string',
        'observacoes_mes2' => '?string',
        'observacoes_mes3' => '?string',
        'observacoes_mes4' => '?string',
        'observacoes_mes5' => '?string',
        'observacoes_mes6' => '?string',
        'observacoes_mes7' => '?string',
        'observacoes_sub1' => '?string',
        'observacoes_sub2' => '?string',
        'preservar_edicao_mes1' => '?bool',
        'preservar_edicao_mes2' => '?bool',
        'preservar_edicao_mes3' => '?bool',
        'preservar_edicao_mes4' => '?bool',
        'preservar_edicao_mes5' => '?bool',
        'preservar_edicao_mes6' => '?bool',
        'preservar_edicao_mes7' => '?bool',
        'preservar_edicao_sub1' => '?bool',
        'preservar_edicao_sub2' => '?bool',
    ];
}
