<?php

namespace App\Entities;

class EiOrdemServicoProfissional extends AbstractEntity
{
	protected $datamap = [];
	protected $dates   = [
		'created_at',
		'updated_at',
		'deleted_at',
	];
	protected $casts   = [
        'id' => 'int',
        'id_ordem_servico_escola' => 'int',
        'id_usuario' => 'int',
        'id_supervisor' => '?int',
        'id_usuario_sub1' => '?int',
        'data_substituicao1' => '?date',
        'id_usuario_sub2' => '?int',
        'data_substituicao2' => '?date',
        'id_departamento' => '?int',
        'id_area' => '?int',
        'id_setor' => '?int',
        'id_cargo' => '?int',
        'id_funcao' => '?int',
        'id_funcao_2m' => '?int',
        'id_funcao_3m' => '?int',
        'id_funcao_1t' => '?int',
        'id_funcao_2t' => '?int',
        'id_funcao_3t' => '?int',
        'id_funcao_1n' => '?int',
        'id_funcao_2n' => '?int',
        'id_funcao_3n' => '?int',
        'municipio' => '?string',
        'valor_hora' => '?decimal',
        'qtde_dias' => '?int',
        'qtde_semanas' => '?int',
        'horas_diarias' => '?decimal',
        'horas_semanais' => '?decimal',
        'horas_mensais' => '?decimal',
        'horas_semestre' => '?decimal',
        'faturamento_semestral_projetado' => '?decimal',
        'desconto_mensal_1' => 'decimal',
        'desconto_mensal_2' => 'decimal',
        'desconto_mensal_3' => 'decimal',
        'desconto_mensal_4' => 'decimal',
        'desconto_mensal_5' => 'decimal',
        'valor_hora_operacional' => '?decimal',
        'valor_hora_operacional_2' => '?decimal',
        'valor_hora_operacional_3' => '?decimal',
        'valor_hora_operacional_1t' => '?decimal',
        'valor_hora_operacional_2t' => '?decimal',
        'valor_hora_operacional_3t' => '?decimal',
        'valor_hora_operacional_1n' => '?decimal',
        'valor_hora_operacional_2n' => '?decimal',
        'valor_hora_operacional_3n' => '?decimal',
        'valor_mensal_1' => '?decimal',
        'valor_mensal_2' => '?decimal',
        'valor_mensal_3' => '?decimal',
        'valor_mensal_4' => '?decimal',
        'valor_mensal_5' => '?decimal',
        'valor_mensal_6' => '?decimal',
        'desconto_mensal_6' => 'decimal',
        'valor_hora_mensal' => '?decimal',
        'desconto_mensal_sub1_1' => 'decimal',
        'desconto_mensal_sub1_2' => 'decimal',
        'desconto_mensal_sub1_3' => 'decimal',
        'desconto_mensal_sub1_4' => 'decimal',
        'desconto_mensal_sub1_5' => 'decimal',
        'desconto_mensal_sub1_6' => 'decimal',
        'desconto_mensal_sub2_1' => 'decimal',
        'desconto_mensal_sub2_2' => 'decimal',
        'desconto_mensal_sub2_3' => 'decimal',
        'desconto_mensal_sub2_4' => 'decimal',
        'desconto_mensal_sub2_5' => 'decimal',
        'desconto_mensal_sub2_6' => 'decimal',
        'horas_mensais_custo' => '?time',
        'horas_mensais_custo_2' => '?time',
        'horas_mensais_custo_3' => '?time',
        'horas_mensais_custo_1t' => '?time',
        'horas_mensais_custo_2t' => '?time',
        'horas_mensais_custo_3t' => '?time',
        'horas_mensais_custo_1n' => '?time',
        'horas_mensais_custo_2n' => '?time',
        'horas_mensais_custo_3n' => '?time',
        'data_inicio_contrato' => '?date',
        'data_termino_contrato' => '?date',
        'pagamento_inicio' => '?decimal',
        'pagamento_reajuste' => '?decimal',
    ];
}
