<?php

namespace App\Entities;

class IcomApontamento extends AbstractEntity
{
	protected $datamap = [];
	protected $dates   = [
		'created_at',
		'updated_at',
		'deleted_at',
	];
	protected $casts   = [
        'id' => 'int',
        'id_alocado' => 'int',
        'data' => 'date',
        'tipo_evento' => 'string',
        'modo_acesso' => '?string',
        'tipo_evento_entrada' => '?string',
        'tipo_evento_saida' => '?string',
        'folga' => '?bool',
        'horario_especial' => '?bool',
        'horario_fracionado' => '?bool',
        'horario_entrada_especial' => '?time',
        'horario_saida_especial' => '?time',
        'qtde_horas_diarias' => '?time',
        'qtde_minutos_folga' => '?time',
        'horario_entrada_especial_2' => '?time',
        'horario_saida_especial_2' => '?time',
        'qtde_horas_diarias_2' => '?time',
        'qtde_minutos_folga_2' => '?time',
        'horario_entrada_especial_3' => '?time',
        'horario_saida_especial_3' => '?time',
        'qtde_horas_diarias_3' => '?time',
        'qtde_minutos_folga_3' => '?time',
        'horario_entrada' => '?time',
        'horario_intervalo' => '?time',
        'horario_retorno' => '?time',
        'horario_saida' => '?time',
        'hora_extra' => '?time',
        'desconto_folha' => '?time',
        'desconto_folha_saida' => '?time',
        'credito_folha' => '?time',
        'banco_horas' => '?time',
        'saldo_banco_horas' => '?time',
        'saida_banco_horas' => '?time',
        'observacoes' => '?string',
        'tipo_evento_2' => '?string',
        'modo_acesso_2' => '?string',
        'tipo_evento_entrada_2' => '?string',
        'tipo_evento_saida_2' => '?string',
        'horario_entrada_2' => '?time',
        'horario_intervalo_2' => '?time',
        'horario_retorno_2' => '?time',
        'horario_saida_2' => '?time',
        'desconto_folha_2' => '?time',
        'desconto_folha_saida_2' => '?time',
        'credito_folha_2' => '?time',
        'saldo_banco_horas_2' => '?time',
        'saida_banco_horas_2' => '?time',
        'observacoes_2' => '?string',
        'tipo_evento_3' => '?string',
        'modo_acesso_3' => '?string',
        'tipo_evento_entrada_3' => '?string',
        'tipo_evento_saida_3' => '?string',
        'horario_entrada_3' => '?time',
        'horario_intervalo_3' => '?time',
        'horario_retorno_3' => '?time',
        'horario_saida_3' => '?time',
        'desconto_folha_3' => '?time',
        'desconto_folha_saida_3' => '?time',
        'credito_folha_3' => '?time',
        'saldo_banco_horas_3' => '?time',
        'saida_banco_horas_3' => '?time',
        'observacoes_3' => '?string',
    ];
}
