<?php

namespace App\Models;

use App\Entities\EiPagamentoPrestador;

class EiPagamentoPrestadorModel extends AbstractModel
{
	protected $DBGroup              = 'default';
	protected $table                = 'ei_pagamentos_prestadores';
	protected $primaryKey           = 'id';
	protected $useAutoIncrement     = true;
	protected $insertID             = 0;
	protected $returnType           = EiPagamentoPrestador::class;
	protected $useSoftDeletes       = false;
	protected $protectFields        = true;
	protected $allowedFields        = [
        'id_alocacao',
        'id_cuidador',
        'cuidador',
        'cargo',
        'cargo_mes2',
        'cargo_mes3',
        'cargo_mes4',
        'cargo_mes5',
        'cargo_mes6',
        'cargo_mes7',
        'funcao',
        'funcao_mes2',
        'funcao_mes3',
        'funcao_mes4',
        'funcao_mes5',
        'funcao_mes6',
        'funcao_mes7',
        'id_substituto',
        'nome_substituto',
        'funcao_substituto',
        'mes_substituticao',
        'nota_complementar',
        'id_complementar_1',
        'id_complementar_2',
        'nota_fiscal_mes1',
        'nota_fiscal_mes2',
        'nota_fiscal_mes3',
        'nota_fiscal_mes4',
        'nota_fiscal_mes5',
        'nota_fiscal_mes6',
        'nota_fiscal_mes7',
        'nota_fiscal_sub',
        'data_solicitacao_nota_mes1',
        'data_solicitacao_nota_mes2',
        'data_solicitacao_nota_mes3',
        'data_solicitacao_nota_mes4',
        'data_solicitacao_nota_mes5',
        'data_solicitacao_nota_mes6',
        'data_solicitacao_nota_mes7',
        'data_solicitacao_nota_sub',
        'data_emissao_mes1',
        'data_emissao_mes2',
        'data_emissao_mes3',
        'data_emissao_mes4',
        'data_emissao_mes5',
        'data_emissao_mes6',
        'data_emissao_mes7',
        'data_emissao_sub',
        'codigo_alfa_mes1',
        'codigo_alfa_mes2',
        'codigo_alfa_mes3',
        'codigo_alfa_mes4',
        'codigo_alfa_mes5',
        'codigo_alfa_mes6',
        'codigo_alfa_mes7',
        'codigo_alfa_sub',
        'valor_extra1_mes1',
        'valor_extra1_mes2',
        'valor_extra1_mes3',
        'valor_extra1_mes4',
        'valor_extra1_mes5',
        'valor_extra1_mes6',
        'valor_extra1_mes7',
        'valor_extra1_sub',
        'valor_extra2_mes1',
        'valor_extra2_mes2',
        'valor_extra2_mes3',
        'valor_extra2_mes4',
        'valor_extra2_mes5',
        'valor_extra2_mes6',
        'valor_extra2_mes7',
        'valor_extra2_sub',
        'justificativa1_mes1',
        'justificativa1_mes2',
        'justificativa1_mes3',
        'justificativa1_mes4',
        'justificativa1_mes5',
        'justificativa1_mes6',
        'justificativa1_sub',
        'justificativa1_mes7',
        'justificativa2_mes1',
        'justificativa2_mes2',
        'justificativa2_mes3',
        'justificativa2_mes4',
        'justificativa2_mes5',
        'justificativa2_mes6',
        'justificativa2_mes7',
        'justificativa2_sub',
        'data_liberacao_pagto_mes1',
        'data_liberacao_pagto_mes2',
        'data_liberacao_pagto_mes3',
        'data_liberacao_pagto_mes4',
        'data_liberacao_pagto_mes5',
        'data_liberacao_pagto_mes6',
        'data_liberacao_pagto_mes7',
        'data_liberacao_pagto_sub',
        'data_inicio_contrato_mes1',
        'data_inicio_contrato_mes2',
        'data_inicio_contrato_mes3',
        'data_inicio_contrato_mes4',
        'data_inicio_contrato_mes5',
        'data_inicio_contrato_mes6',
        'data_inicio_contrato_mes7',
        'data_inicio_contrato_sub',
        'data_termino_contrato_mes1',
        'data_termino_contrato_mes2',
        'data_termino_contrato_mes3',
        'data_termino_contrato_mes4',
        'data_termino_contrato_mes5',
        'data_termino_contrato_mes6',
        'data_termino_contrato_mes7',
        'data_termino_contrato_sub',
        'falta_anterior_mes1',
        'falta_anterior_mes2',
        'falta_anterior_mes3',
        'falta_anterior_mes4',
        'falta_anterior_mes5',
        'falta_anterior_mes6',
        'falta_anterior_mes7',
        'falta_anterior_sub',
        'falta_atual_mes1',
        'falta_atual_mes2',
        'falta_atual_mes3',
        'falta_atual_mes4',
        'falta_atual_mes5',
        'falta_atual_mes6',
        'falta_atual_mes7',
        'falta_atual_sub',
        'falta_posterior_mes7',
        'desconto_anterior_mes1',
        'desconto_anterior_mes2',
        'desconto_anterior_mes3',
        'desconto_anterior_mes4',
        'desconto_anterior_mes5',
        'desconto_anterior_mes6',
        'desconto_anterior_mes7',
        'desconto_anterior_sub',
        'desconto_atual_mes1',
        'desconto_atual_mes2',
        'desconto_atual_mes3',
        'desconto_atual_mes4',
        'desconto_atual_mes5',
        'desconto_atual_mes6',
        'desconto_atual_mes7',
        'desconto_atual_sub',
        'desconto_posterior_mes7',
        'pagamento_proporcional_inicio',
        'pagamento_proporcional_termino',
        'tipo_pagamento_mes1',
        'tipo_pagamento_mes2',
        'tipo_pagamento_mes3',
        'tipo_pagamento_mes4',
        'tipo_pagamento_mes5',
        'tipo_pagamento_mes6',
        'tipo_pagamento_mes7',
        'tipo_pagamento_sub',
        'status_mes1',
        'status_mes2',
        'status_mes3',
        'status_mes4',
        'status_mes5',
        'status_mes6',
        'status_mes7',
        'status_sub',
        'arquivo_nota_fiscal_mes1',
        'arquivo_nota_fiscal_mes2',
        'arquivo_nota_fiscal_mes3',
        'arquivo_nota_fiscal_mes4',
        'arquivo_nota_fiscal_mes5',
        'arquivo_nota_fiscal_mes6',
        'arquivo_nota_fiscal_mes7',
        'arquivo_nota_fiscal_sub',
        'validacao_nota_fiscal_mes1',
        'validacao_nota_fiscal_mes2',
        'validacao_nota_fiscal_mes3',
        'validacao_nota_fiscal_mes4',
        'validacao_nota_fiscal_mes5',
        'validacao_nota_fiscal_mes6',
        'validacao_nota_fiscal_mes7',
        'validacao_nota_fiscal_sub',
        'observacoes_mes1',
        'observacoes_mes2',
        'observacoes_mes3',
        'observacoes_mes4',
        'observacoes_mes5',
        'observacoes_mes6',
        'observacoes_mes7',
        'observacoes_sub',
        'mes_competencia_1',
        'mes_competencia_2',
        'mes_competencia_3',
        'mes_competencia_4',
        'mes_competencia_5',
        'mes_competencia_6',
        'mes_competencia_7',
        'mes_competencia_sub',
        'preservar_edicao_mes1',
        'preservar_edicao_mes2',
        'preservar_edicao_mes3',
        'preservar_edicao_mes4',
        'preservar_edicao_mes5',
        'preservar_edicao_mes6',
        'preservar_edicao_mes7',
        'preservar_edicao_sub',
        'data_criacao_mes1',
        'data_criacao_mes2',
        'data_criacao_mes3',
        'data_criacao_mes4',
        'data_criacao_mes5',
        'data_criacao_mes6',
        'data_criacao_mes7',
        'data_criacao_sub',
    ];

	// Dates
	protected $useTimestamps        = false;
	protected $dateFormat           = 'datetime';
	protected $createdField         = 'created_at';
	protected $updatedField         = 'updated_at';
	protected $deletedField         = 'deleted_at';

	// Validation
	protected $validationRules      = [
        'id_alocacao'                       => 'required|is_natural_no_zero|max_length[11]',
        'id_cuidador'                       => 'is_natural_no_zero|max_length[11]',
        'cuidador'                          => 'string|max_length[255]',
        'cargo'                             => 'string|max_length[255]',
        'cargo_mes2'                        => 'string|max_length[255]',
        'cargo_mes3'                        => 'string|max_length[255]',
        'cargo_mes4'                        => 'string|max_length[255]',
        'cargo_mes5'                        => 'string|max_length[255]',
        'cargo_mes6'                        => 'string|max_length[255]',
        'cargo_mes7'                        => 'string|max_length[255]',
        'funcao'                            => 'string|max_length[255]',
        'funcao_mes2'                       => 'string|max_length[255]',
        'funcao_mes3'                       => 'string|max_length[255]',
        'funcao_mes4'                       => 'string|max_length[255]',
        'funcao_mes5'                       => 'string|max_length[255]',
        'funcao_mes6'                       => 'string|max_length[255]',
        'funcao_mes7'                       => 'string|max_length[255]',
        'id_substituto'                     => 'integer|max_length[11]',
        'nome_substituto'                   => 'string|max_length[255]',
        'funcao_substituto'                 => 'string|max_length[255]',
        'mes_substituticao'                 => 'integer|exact_length[1]',
        'nota_complementar'                 => 'integer|exact_length[1]',
        'id_complementar_1'                 => 'is_natural_no_zero|max_length[11]',
        'id_complementar_2'                 => 'is_natural_no_zero|max_length[11]',
        'nota_fiscal_mes1'                  => 'string|max_length[255]',
        'nota_fiscal_mes2'                  => 'string|max_length[255]',
        'nota_fiscal_mes3'                  => 'string|max_length[255]',
        'nota_fiscal_mes4'                  => 'string|max_length[255]',
        'nota_fiscal_mes5'                  => 'string|max_length[255]',
        'nota_fiscal_mes6'                  => 'string|max_length[255]',
        'nota_fiscal_mes7'                  => 'string|max_length[255]',
        'nota_fiscal_sub'                   => 'string|max_length[255]',
        'data_solicitacao_nota_mes1'        => 'valid_date',
        'data_solicitacao_nota_mes2'        => 'valid_date',
        'data_solicitacao_nota_mes3'        => 'valid_date',
        'data_solicitacao_nota_mes4'        => 'valid_date',
        'data_solicitacao_nota_mes5'        => 'valid_date',
        'data_solicitacao_nota_mes6'        => 'valid_date',
        'data_solicitacao_nota_mes7'        => 'valid_date',
        'data_solicitacao_nota_sub'         => 'valid_date',
        'data_emissao_mes1'                 => 'valid_date',
        'data_emissao_mes2'                 => 'valid_date',
        'data_emissao_mes3'                 => 'valid_date',
        'data_emissao_mes4'                 => 'valid_date',
        'data_emissao_mes5'                 => 'valid_date',
        'data_emissao_mes6'                 => 'valid_date',
        'data_emissao_mes7'                 => 'valid_date',
        'data_emissao_sub'                  => 'valid_date',
        'codigo_alfa_mes1'                  => 'string|max_length[100]',
        'codigo_alfa_mes2'                  => 'string|max_length[100]',
        'codigo_alfa_mes3'                  => 'string|max_length[100]',
        'codigo_alfa_mes4'                  => 'string|max_length[100]',
        'codigo_alfa_mes5'                  => 'string|max_length[100]',
        'codigo_alfa_mes6'                  => 'string|max_length[100]',
        'codigo_alfa_mes7'                  => 'string|max_length[100]',
        'codigo_alfa_sub'                   => 'string|max_length[100]',
        'valor_extra1_mes1'                 => 'numeric|max_length[10]',
        'valor_extra1_mes2'                 => 'numeric|max_length[10]',
        'valor_extra1_mes3'                 => 'numeric|max_length[10]',
        'valor_extra1_mes4'                 => 'numeric|max_length[10]',
        'valor_extra1_mes5'                 => 'numeric|max_length[10]',
        'valor_extra1_mes6'                 => 'numeric|max_length[10]',
        'valor_extra1_mes7'                 => 'numeric|max_length[10]',
        'valor_extra1_sub'                  => 'numeric|max_length[10]',
        'valor_extra2_mes1'                 => 'numeric|max_length[10]',
        'valor_extra2_mes2'                 => 'numeric|max_length[10]',
        'valor_extra2_mes3'                 => 'numeric|max_length[10]',
        'valor_extra2_mes4'                 => 'numeric|max_length[10]',
        'valor_extra2_mes5'                 => 'numeric|max_length[10]',
        'valor_extra2_mes6'                 => 'numeric|max_length[10]',
        'valor_extra2_mes7'                 => 'numeric|max_length[10]',
        'valor_extra2_sub'                  => 'numeric|max_length[10]',
        'justificativa1_mes1'               => 'string',
        'justificativa1_mes2'               => 'string',
        'justificativa1_mes3'               => 'string',
        'justificativa1_mes4'               => 'string',
        'justificativa1_mes5'               => 'string',
        'justificativa1_mes6'               => 'string',
        'justificativa1_sub'                => 'string',
        'justificativa1_mes7'               => 'string',
        'justificativa2_mes1'               => 'string',
        'justificativa2_mes2'               => 'string',
        'justificativa2_mes3'               => 'string',
        'justificativa2_mes4'               => 'string',
        'justificativa2_mes5'               => 'string',
        'justificativa2_mes6'               => 'string',
        'justificativa2_mes7'               => 'string',
        'justificativa2_sub'                => 'string',
        'data_liberacao_pagto_mes1'         => 'valid_date',
        'data_liberacao_pagto_mes2'         => 'valid_date',
        'data_liberacao_pagto_mes3'         => 'valid_date',
        'data_liberacao_pagto_mes4'         => 'valid_date',
        'data_liberacao_pagto_mes5'         => 'valid_date',
        'data_liberacao_pagto_mes6'         => 'valid_date',
        'data_liberacao_pagto_mes7'         => 'valid_date',
        'data_liberacao_pagto_sub'          => 'valid_date',
        'data_inicio_contrato_mes1'         => 'valid_date',
        'data_inicio_contrato_mes2'         => 'valid_date',
        'data_inicio_contrato_mes3'         => 'valid_date',
        'data_inicio_contrato_mes4'         => 'valid_date',
        'data_inicio_contrato_mes5'         => 'valid_date',
        'data_inicio_contrato_mes6'         => 'valid_date',
        'data_inicio_contrato_mes7'         => 'valid_date',
        'data_inicio_contrato_sub'          => 'valid_date',
        'data_termino_contrato_mes1'        => 'valid_date',
        'data_termino_contrato_mes2'        => 'valid_date',
        'data_termino_contrato_mes3'        => 'valid_date',
        'data_termino_contrato_mes4'        => 'valid_date',
        'data_termino_contrato_mes5'        => 'valid_date',
        'data_termino_contrato_mes6'        => 'valid_date',
        'data_termino_contrato_mes7'        => 'valid_date',
        'data_termino_contrato_sub'         => 'valid_date',
        'falta_anterior_mes1'               => 'valid_time',
        'falta_anterior_mes2'               => 'valid_time',
        'falta_anterior_mes3'               => 'valid_time',
        'falta_anterior_mes4'               => 'valid_time',
        'falta_anterior_mes5'               => 'valid_time',
        'falta_anterior_mes6'               => 'valid_time',
        'falta_anterior_mes7'               => 'valid_time',
        'falta_anterior_sub'                => 'valid_time',
        'falta_atual_mes1'                  => 'valid_time',
        'falta_atual_mes2'                  => 'valid_time',
        'falta_atual_mes3'                  => 'valid_time',
        'falta_atual_mes4'                  => 'valid_time',
        'falta_atual_mes5'                  => 'valid_time',
        'falta_atual_mes6'                  => 'valid_time',
        'falta_atual_mes7'                  => 'valid_time',
        'falta_atual_sub'                   => 'valid_time',
        'falta_posterior_mes7'              => 'valid_time',
        'desconto_anterior_mes1'            => 'valid_time',
        'desconto_anterior_mes2'            => 'valid_time',
        'desconto_anterior_mes3'            => 'valid_time',
        'desconto_anterior_mes4'            => 'valid_time',
        'desconto_anterior_mes5'            => 'valid_time',
        'desconto_anterior_mes6'            => 'valid_time',
        'desconto_anterior_mes7'            => 'valid_time',
        'desconto_anterior_sub'             => 'valid_time',
        'desconto_atual_mes1'               => 'valid_time',
        'desconto_atual_mes2'               => 'valid_time',
        'desconto_atual_mes3'               => 'valid_time',
        'desconto_atual_mes4'               => 'valid_time',
        'desconto_atual_mes5'               => 'valid_time',
        'desconto_atual_mes6'               => 'valid_time',
        'desconto_atual_mes7'               => 'valid_time',
        'desconto_atual_sub'                => 'valid_time',
        'desconto_posterior_mes7'           => 'valid_time',
        'pagamento_proporcional_inicio'     => 'integer|exact_length[1]',
        'pagamento_proporcional_termino'    => 'integer|exact_length[1]',
        'tipo_pagamento_mes1'               => 'integer|exact_length[1]',
        'tipo_pagamento_mes2'               => 'integer|exact_length[1]',
        'tipo_pagamento_mes3'               => 'integer|exact_length[1]',
        'tipo_pagamento_mes4'               => 'integer|exact_length[1]',
        'tipo_pagamento_mes5'               => 'integer|exact_length[1]',
        'tipo_pagamento_mes6'               => 'integer|exact_length[1]',
        'tipo_pagamento_mes7'               => 'integer|exact_length[1]',
        'tipo_pagamento_sub'                => 'integer|exact_length[1]',
        'status_mes1'                       => 'integer|exact_length[1]',
        'status_mes2'                       => 'integer|exact_length[1]',
        'status_mes3'                       => 'integer|exact_length[1]',
        'status_mes4'                       => 'integer|exact_length[1]',
        'status_mes5'                       => 'integer|exact_length[1]',
        'status_mes6'                       => 'integer|exact_length[1]',
        'status_mes7'                       => 'integer|exact_length[1]',
        'status_sub'                        => 'integer|exact_length[1]',
        'arquivo_nota_fiscal_mes1'          => 'string|max_length[255]',
        'arquivo_nota_fiscal_mes2'          => 'string|max_length[255]',
        'arquivo_nota_fiscal_mes3'          => 'string|max_length[255]',
        'arquivo_nota_fiscal_mes4'          => 'string|max_length[255]',
        'arquivo_nota_fiscal_mes5'          => 'string|max_length[255]',
        'arquivo_nota_fiscal_mes6'          => 'string|max_length[255]',
        'arquivo_nota_fiscal_mes7'          => 'string|max_length[255]',
        'arquivo_nota_fiscal_sub'           => 'string|max_length[255]',
        'validacao_nota_fiscal_mes1'        => 'integer|exact_length[1]',
        'validacao_nota_fiscal_mes2'        => 'integer|exact_length[1]',
        'validacao_nota_fiscal_mes3'        => 'integer|exact_length[1]',
        'validacao_nota_fiscal_mes4'        => 'integer|exact_length[1]',
        'validacao_nota_fiscal_mes5'        => 'integer|exact_length[1]',
        'validacao_nota_fiscal_mes6'        => 'integer|exact_length[1]',
        'validacao_nota_fiscal_mes7'        => 'integer|exact_length[1]',
        'validacao_nota_fiscal_sub'         => 'integer|exact_length[1]',
        'observacoes_mes1'                  => 'string',
        'observacoes_mes2'                  => 'string',
        'observacoes_mes3'                  => 'string',
        'observacoes_mes4'                  => 'string',
        'observacoes_mes5'                  => 'string',
        'observacoes_mes6'                  => 'string',
        'observacoes_mes7'                  => 'string',
        'observacoes_sub'                   => 'string',
        'mes_competencia_1'                 => 'integer|exact_length[1]',
        'mes_competencia_2'                 => 'integer|exact_length[1]',
        'mes_competencia_3'                 => 'integer|exact_length[1]',
        'mes_competencia_4'                 => 'integer|exact_length[1]',
        'mes_competencia_5'                 => 'integer|exact_length[1]',
        'mes_competencia_6'                 => 'integer|exact_length[1]',
        'mes_competencia_7'                 => 'integer|exact_length[1]',
        'mes_competencia_sub'               => 'integer|exact_length[1]',
        'preservar_edicao_mes1'             => 'integer|exact_length[1]',
        'preservar_edicao_mes2'             => 'integer|exact_length[1]',
        'preservar_edicao_mes3'             => 'integer|exact_length[1]',
        'preservar_edicao_mes4'             => 'integer|exact_length[1]',
        'preservar_edicao_mes5'             => 'integer|exact_length[1]',
        'preservar_edicao_mes6'             => 'integer|exact_length[1]',
        'preservar_edicao_mes7'             => 'integer|exact_length[1]',
        'preservar_edicao_sub'              => 'integer|exact_length[1]',
        'data_criacao_mes1'                 => 'valid_date',
        'data_criacao_mes2'                 => 'valid_date',
        'data_criacao_mes3'                 => 'valid_date',
        'data_criacao_mes4'                 => 'valid_date',
        'data_criacao_mes5'                 => 'valid_date',
        'data_criacao_mes6'                 => 'valid_date',
        'data_criacao_mes7'                 => 'valid_date',
        'data_criacao_sub'                  => 'valid_date',
    ];
	protected $validationMessages   = [];
	protected $skipValidation       = false;
	protected $cleanValidationRules = true;

	// Callbacks
	protected $allowCallbacks       = true;
	protected $beforeInsert         = [];
	protected $afterInsert          = [];
	protected $beforeUpdate         = [];
	protected $afterUpdate          = [];
	protected $beforeFind           = [];
	protected $afterFind            = [];
	protected $beforeDelete         = [];
	protected $afterDelete          = [];

    //--------------------------------------------------------------------

    protected $uploadConfig = [
        'arquivo_nota_fiscal_mes1' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
        'arquivo_nota_fiscal_mes2' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
        'arquivo_nota_fiscal_mes3' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
        'arquivo_nota_fiscal_mes4' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
        'arquivo_nota_fiscal_mes5' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
        'arquivo_nota_fiscal_mes6' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
        'arquivo_nota_fiscal_mes7' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
        'arquivo_nota_fiscal_sub' => ['upload_path' => './arquivos/ei/notas_fiscais/', 'allowed_types' => 'pdf'],
    ];

    public const STATUS = [
        '' => 'Validar valor',
        '1' => 'Eu concordo com o valor a ser pago',
        '2' => 'Eu não concordo com o valor a ser pago',
        '3' => 'Carta de correção',
        '4' => 'Nota complementar',
    ];

    //--------------------------------------------------------------------

    protected function renomearArquivosNotasFiscais($data): array
    {
        if (is_null($data['data'])) {
            return $data;
        }

        $cuidador = $this->db
            ->select('nome, cnpj')
            ->where('id', $data['data']['id_cuidador'] ?? session('id'))
            ->get('usuarios')
            ->row();

        if (empty($cuidador)) {
            return $data;
        }

        $alocacao = $this->db
            ->where('id', $data['data']['id_alocacao'] ?? null)
            ->get('ei_alocacoes')
            ->row();

        $ano = $alocacao->ano ?? date('Y');
        $mesesSemestre = $alocacao->semestre > 1 ? 6 : 0;
        $cuidador->nome = str_replace(' ', '_', trim($cuidador->nome));
        $cuidador->cnpj = str_replace([' ', '.', '/'], ['_', '_', ''], trim($cuidador->cnpj));
        $uploadConfig = $this->uploadConfig;

        foreach ($uploadConfig as $file => &$config) {
            if (array_key_exists($file, $data['data']) and !is_null($data['data'][$file]) and isset($_FILES[$file])) {
                $mes = preg_replace('/[^0-9]/', '', $file);
                $mes = str_pad($mes, 2, '0', STR_PAD_LEFT);
                $type = !empty($_FILES[$file]['name']) ? strstr($_FILES[$file]['name'], '.') : null;
                $config['file_name'] = implode('-', ['EI', $ano . $mes, $cuidador->nome, $cuidador->cnpj]) . $type;
                $data['data'][$file] = $config['file_name'];
            }
        }

        $this->uploadConfig = $uploadConfig;

        return $data;
    }
}
