<?php

namespace App\Models;

use App\Entities\Empresa;
use CodeIgniter\Model;

class EmpresaModel extends Model
{
    protected $DBGroup              = 'default';
    protected $table                = 'empresas';
    protected $primaryKey           = 'id_usuario';
    protected $useAutoIncrement     = false;
    protected $insertID             = 0;
    protected $returnType           = Empresa::class;
    protected $useSoftDeletes       = false;
    protected $protectFields        = true;
    protected $allowedFields        = [
        'id_usuario',
        'nome',
        'url',
        'foto',
        'foto_descricao',
        'cabecalho',
        'imagem_inicial',
        'tipo_tela_inicial',
        'imagem_fundo',
        'video_fundo',
        'assinatura_digital',
        'hash_acesso',
        'max_colaboradores',
        'visualizacao_pilula_conhecimento',
        'visualizacao_rodape',
        'status',
    ];

    // Dates
    protected $useTimestamps        = false;
    protected $dateFormat           = 'datetime';
    protected $createdField         = 'created_at';
    protected $updatedField         = 'updated_at';
    protected $deletedField         = 'deleted_at';

    // Validation
    protected $validationRules      = [
        'id_usuario'                        => 'required|is_natural_no_zero|max_length[11]',
        'nome'                              => 'required|string|max_length[255]',
        'url'                               => 'required|string|max_length[255]',
        'foto'                              => 'required|string|max_length[255]',
        'foto_descricao'                    => 'string|max_length[255]',
        'cabecalho'                         => 'string',
        'imagem_inicial'                    => 'required|string',
        'tipo_tela_inicial'                 => 'required|integer|exact_length[1]',
        'imagem_fundo'                      => 'string',
        'video_fundo'                       => 'string',
        'assinatura_digital'                => 'string',
        'hash_acesso'                       => 'string',
        'max_colaboradores'                 => 'integer|max_length[11]',
        'visualizacao_pilula_conhecimento'  => 'integer|exact_length[1]',
        'visualizacao_rodape'               => 'integer|exact_length[1]',
        'status'                            => 'integer|exact_length[1]',
    ];
    protected $validationMessages   = [];
    protected $skipValidation       = false;
    protected $cleanValidationRules = true;

    // Callbacks
    protected $allowCallbacks       = true;
    protected $beforeInsert         = [];
    protected $afterInsert          = [];
    protected $beforeUpdate         = [];
    protected $afterUpdate          = [];
    protected $beforeFind           = [];
    protected $afterFind            = [];
    protected $beforeDelete         = [];
    protected $afterDelete          = [];

    //--------------------------------------------------------------------

    protected $uploadConfig = [
        'foto' => ['upload_path' => './imagens/usuarios/', 'allowed_types' => 'gif|jpg|png'],
        'foto_descricao' => ['upload_path' => './imagens/usuarios/', 'allowed_types' => 'gif|jpg|png'],
        'imagem_inicial' => ['upload_path' => './imagens/usuarios/', 'allowed_types' => 'gif|jpg|png'],
        'imagem_fundo' => ['upload_path' => './imagens/usuarios/', 'allowed_types' => 'jpg|png'],
        'video_fundo' => ['upload_path' => './videos/usuarios/', 'allowed_types' => 'mp4'],
        'assinatura_digital' => ['upload_path' => './imagens/usuarios/', 'allowed_types' => 'gif|jpg|png']
    ];

    public const STATUS = [
        '1' => 'Ativa',
        '0' => 'Bloqueada',
    ];

    public function insert($data = null, bool $returnID = true)
    {
        $this->setValidationRule('id_usuario', 'required|is_natural_no_zero|max_length[11]|is_unique[empresa.id_usuario,id_usuario,{id_usuario}]');
        return parent::insert($data, $returnID); // TODO: Change the autogenerated stub
    }

    public function insertBatch(?array $set = null, ?bool $escape = null, int $batchSize = 100, bool $testing = false)
    {
        $this->setValidationRule('id_usuario', 'required|is_natural_no_zero|max_length[11]|is_unique[empresa.id_usuario,id_usuario,{id_usuario}]');
        return parent::insertBatch($set, $escape, $batchSize, $testing); // TODO: Change the autogenerated stub
    }
}
